inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop_custom.yml
  - .rubocop/strict.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: true
  NewCops: enable
  TargetRubyVersion: 2.7
